server:
  port: 60301

spring:
  application:
    name: Kerugoya_Bursary_Automation

  datasource:
    url: jdbc:postgresql://localhost:5432/kerugoya_bursary
    username: titus
    password: 123456789
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
